### PR TITLE
Monospace font for update details

### PR DESCRIPTION
**Pull request by alimirjamali**
Changing the current `Source Sans Pro` font used for update progress detail text box to `Source Code Pro`

Reference to issue: Fixes https://github.com/QubesOS/qubes-issues/issues/9235

### CODE REVIEW

**Review by marmarta — CHANGES_REQUESTED** [review]

**Comment by marmarta** [comment]
Ignore failing pylint here, on rebase to newest main it should be fixed.

**Comment by alimirjamali** [comment]
> I don't think this font is available in dom0 by default (in my 4.2 install I don't have it);

Now that I look, I see that neither of `Source` family of fonts is installed in dom0 in my machine. Perhaps the CSS template had it by default. I lack knowledge on GTK behaviour on missing fonts and the fallback mechanism. There is a [mention](https://docs.gtk.org/gtk3/property.TextTag.fallback.html) of this in GTK documentation but not the details.

**Comment by alimirjamali** [comment]
@marmarta This was the other commit that had ended up on the other issue.

I changed the `font-family` for Qubes Update GUI progress area to `monospace`. As it was advised in the previous conversation.

**Review by marmarta — APPROVED** [review]

**Comment by marmarta** [comment]
QA fail is due to https://github.com/pylint-dev/astroid/issues/2190, so should not be considered blocking.

**Comment by alimirjamali** [comment]
> I think our font situation is a bit of a mess.. We use fonts very inconsistently, I think the fact that it's not in dom0 is not great (and yeah, can't see it on mine, either). I'm going to make an issue for that..

Even though this PR is merged & closed. I believe the default `monospace` font used by GTK is not very nice. I wonder if you would still consider the above (deciding on the preferred Monospace font for GUI applications which should be installed by default in GUIVM).

Whatever GTK decided to revert to for `Source Code Pro` is much better than the default monospace.

**Comment by marmarta** [comment]
I am going to be working with a lovely designer team on a UX audit for Qubes OS soon, and I think that setting on a single set of sans and monospace fonts will be a part of it. I am taking note of this comment and yeah, I think you're right here.

**Pull request merged**
