### PR TITLE
sort by name device/domain 

### PR DESCRIPTION
**Pull request by adavida**
it would bother me, it was not sorted by name

I have remedied this problem

david

### CODE REVIEW

**Comment by adavida** [comment]
sorry I forgot to sign.
I went back with the command "git reset a720bda3"
then I made a commit with option S

I do not know, if it worked

**Comment by marmarek** [comment]
Have you uploaded public key anywhere? It isn't linked to your github account and also I can't find it on keyservers.

**Comment by adavida** [comment]
I followed the instructions on the page:https://www.qubes-os.org/doc/code-signing/

Can you tell me how to proceed to link the key to my github account?
thank you

**Comment by marmarek** [comment]
See here: https://help.github.com/articles/associating-an-email-with-your-gpg-key/

**Comment by marmarek** [comment]
Or rather: https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/

**Comment by adavida** [comment]
thank you
I did what said on it is 2 page 

on this page https://github.com/adavida/qubes-desktop-linux-manager/commits/master my commit is verified 

but on pull request, i still have : "Unable to verify (no valid key found)"

**Pull request closed without merging**
