### PR TITLE
Improve Qubes OS Update reporting for dom0

### PR DESCRIPTION
**Pull request by alimirjamali**
fixes: https://github.com/QubesOS/qubes-issues/issues/9355

### CODE REVIEW

**Comment by marmarek** [comment]
pylint complains and it seems its correct. I know the old version didn't use `with subproces.Popen(...)`, but since you don't really interact with the process outside of this function, better use `with`. And maybe return just returncode since that's what is used outside?

**Comment by alimirjamali** [comment]
Now that I look again, I see that no error handling is done for the actual update. I will tend to that as well.

**Comment by alimirjamali** [comment]
Ok. It is done. I added an additional check for the actual `qubes-dom0-update -y` to show the red X on dnf errors.

One user had referred to this bug in the Github Issues (I can not find the exact issue). Where if the actual updates fails (e.g. due to network problem or a dnf conflict or anything else), the GUI shows the green check mark.

**Comment by alimirjamali** [comment]
Pylint fails due to curl error during downloading metadata for dnf. What is wrong here?

**Comment by marmarek** [comment]
PipelineRetryFailed

**Review by marmarek — APPROVED** [review]

**Pull request merged**
