### PR TITLE
Uneditable column headers in policy editor

### PR DESCRIPTION
**Pull request by alimirjamali**
Fix for https://github.com/QubesOS/qubes-issues/issues/9061

### CODE REVIEW

**Comment by alimirjamali** [comment]
The other approach on this would be swapping header_view with a Gtk.TreeView with resizeable columns with titles without any data rows. So the user could resize columns as how they desire to format the main Policy file. 

Setting the editable flag to False should address Marek's concern for the time.

**Comment by marmarta** [comment]
> The other approach on this would be swapping header_view with a Gtk.TreeView with resizeable columns with titles without any data rows. So the user could resize columns as how they desire to format the main Policy file.
> 
> Setting the editable flag to False should address Marek's concern for the time.

That's a cool idea! But yeah, it would involve multiple changes, so I think this fix is a very good fix for the issue (and going to TreeView a nice-in-the-future thing).

**Review by marmarta — APPROVED** [review]

**Comment by ben-grande** [comment]
Please reword the commit message https://github.com/QubesOS/qubes-core-agent-linux/pull/505#issuecomment-2182128640

Add `Fixes: URL` to commit body.

**Comment by alimirjamali** [comment]
> Please reword the commit message

Done. Thanks for guide.

**Comment by ben-grande** [comment]
You amended to the merge commit.

**Comment by alimirjamali** [comment]
> You amended to the merge commit.

The amended commit message contains a note on on both. (Keeping with upstream and the fix). Should I amend the old one as well?

**Comment by ben-grande** [comment]
The commit 2adcdfed762d477ff461e9927f0e9011bc82a278 should have the `Fixes` in the body. The merge commit 995ceb9a55d497d0dd0a34ff320eb72e9f673593 should have `Merging upstream branch 'main' into Policy_Editor_Fixes` in the subject.

As you did a merge, the work of rewriting is a little bit more involved than amending the last commit, which is the merge. See [stackoverflow.com/amending-the-message-of-git-commit-made-before-a-merge](https://stackoverflow.com/questions/16539346/amending-the-message-of-git-commit-made-before-a-merge).

**Comment by alimirjamali** [comment]
> The commit [2adcdfe](https://github.com/QubesOS/qubes-desktop-linux-manager/commit/2adcdfed762d477ff461e9927f0e9011bc82a278) should have the `Fixes` in the body. The merge commit [995ceb9](https://github.com/QubesOS/qubes-desktop-linux-manager/commit/995ceb9a55d497d0dd0a34ff320eb72e9f673593) should have `Merging upstream branch 'main' into Policy_Editor_Fixes` in the subject.

Ok. I did a reset --hard to the original commit and amended the commit message. There is no a confusing merge commit anymore.

**Review by marmarta — APPROVED** [review]

**Comment by marmarta** [comment]
Thank you! @marmarek , this is ready

**Pull request merged**
