### PR TITLE
Devices widget: label recently-connected devices as "NEW"

### PR DESCRIPTION
**Pull request by kennethrrosen**
fixes: https://github.com/QubesOS/qubes-issues/issues/8543

### CODE REVIEW

**Comment by kennethrrosen** [comment]
@marmarek I've now pushed the PR with my signing key.

**Review by alimirjamali — APPROVED** [review]

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
pylint:
```
************* Module qui.devices.actionable_widgets
qui/devices/actionable_widgets.py:412:0: C0301: Line too long (101/80) (line-too-long)
```

**Comment by marmarek** [comment]
> system_tests_gui_tools
> 
>     * qui_widgets_devices: [unnamed test](https://openqa.qubes-os.org/tests/105621#step/qui_widgets_devices/6) (unknown)
> 
>     * qui_widgets_devices: [Failed](https://openqa.qubes-os.org/tests/105621#step/qui_widgets_devices/7) (test died)
>       `# Test died: no candidate needle with tag(s) 'qui-devices-opened' m...`

```
Jul 08 01:43:45 dom0 widget-wrapper[2863]: Traceback (most recent call last):
Jul 08 01:43:45 dom0 widget-wrapper[2863]:   File "/usr/lib/python3.11/site-packages/qui/devices/device_widget.py", line 320, in show_menu
Jul 08 01:43:45 dom0 widget-wrapper[2863]:     device_widget = actionable_widgets.MainDeviceWidget(dev, theme)
Jul 08 01:43:45 dom0 widget-wrapper[2863]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 08 01:43:45 dom0 widget-wrapper[2863]:   File "/usr/lib/python3.11/site-packages/qui/devices/actionable_widgets.py", line 412, in __init__
Jul 08 01:43:45 dom0 widget-wrapper[2863]:     if device.connection_timestamp and int(time.monotonic() - device.connection_timestamp) < 120:
Jul 08 01:43:45 dom0 widget-wrapper[2863]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 08 01:43:45 dom0 widget-wrapper[2863]: AttributeError: 'Device' object has no attribute 'connection_timestamp'
```

**Comment by kennethrrosen** [comment]
@marmarek corrected the pylint and initial value error

**Comment by marmarek** [comment]
pylint complains about trailing whitespace...

**Comment by kennethrrosen** [comment]
@marmarek all set. thank you for your patience!

**Comment by marmarta** [comment]
sorry for being a complainer, but: I'm not that sure about two things. One is red color of the font - red is generally a "bad" color, although recently it has also been used for "new stuff". Two is the exclamation mark, which makes it even scarier for a user (at least I get this feeling). Maybe it would be a bit less scary if the NEW was blue, in one of the Qubes Blue colors (e.g. primary blue: https://www.qubes-os.org/doc/visual-style-guide/ )

**Comment by kennethrrosen** [comment]
> sorry for being a complainer, but: I'm not that sure about two things. One is red color of the font - red is generally a "bad" color, although recently it has also been used for "new stuff". Two is the exclamation mark, which makes it even scarier for a user (at least I get this feeling). Maybe it would be a bit less scary if the NEW was blue, in one of the Qubes Blue colors (e.g. primary blue: https://www.qubes-os.org/doc/visual-style-guide/ )

@marmarta  Would adding "qubes-blue" work within the span style, or would I also need to load_css from qubes-colors-dark.css? Using "blue" would also work, but it would be outside the style framework.

**Comment by marmarta** [comment]
> 
> @marmarta Would adding "qubes-blue" work within the span style, or would I also need to load_css from qubes-colors-dark.css? Using "blue" would also work, but it would be outside the style framework.

Sadly, Gtk is not great here and you can't use CSS stuff in span (worse, they literally rejected a PR that would add it, because "they want to go in the direction of more widgets") -  you can just use the literal color number ( #3874d8 or #63a0ff , not sure which would look better, probably the lighter one

**Pull request merged**
