### PR TITLE
Display 0% CPU usage, but with low-contrast color

### PR DESCRIPTION
**Pull request by SaswatPadhi**
A work-in-progress PR for addressing QubesOS/qubes-issues#5195

### CODE REVIEW

**Comment by SaswatPadhi** [comment]
Apparently, this is a travis bug: travis-ci/travis-ci#10132

**Comment by SaswatPadhi** [comment]
Why don't we upgrade our travis build scripts to use `xenial` btw? Seems like this bug only affects `trusty`

**Comment by marmarek** [comment]
> Why don't we upgrade our travis build scripts to use `xenial` btw? Seems like this bug only affects `trusty`

We do that, slowly QubesOS/qubes-issues#4613

**Comment by SaswatPadhi** [comment]
Now that the travis scripts run on `xenial`, is there a way to trigger a rebuild for this PR?

**Comment by marmarek** [comment]
Simply re-rerunning travis build apparently isn't enough. I think you'd need to change something (even commit date should be enough) and force-push. Something like:
```
git commit --amend
git push -f
```

**Comment by SaswatPadhi** [comment]
Thanks @marmarek.

I am not sure why the code-signing script isn't accepting my GPG key. I checked that it exists on [sks-keyservers.net](http://pool.sks-keyservers.net:11371/pks/lookup?search=0xF2C8AE1480DB4E0E&op=vindex)

**Pull request merged**
