### PR TITLE
Issue 8725 - Tray Update Notifier fix for os-eol feature change

### PR DESCRIPTION
**Pull request by alimirjamali**
Fixes https://github.com/QubesOS/qubes-issues/issues/8725

According to @marmarek
> As for the list of obsolete templates in the widget, indeed it looks to not refresh itself.

### CODE REVIEW

**Comment by ben-grande** [comment]
Please reword the commit message https://github.com/QubesOS/qubes-core-agent-linux/pull/505#issuecomment-2182128640

**Comment by alimirjamali** [comment]
> Please reword the commit messag

Done

**Review by marmarta — APPROVED** [review]
This is great. QA fail is random, ignore it.

Also, thank you so much for all the PRs you submitted recently! They are great and very helpful :)

**Comment by alimirjamali** [comment]
> Also, thank you so much for all the PRs you submitted recently! They are great and very helpful :)

Thank you very much for taking time to review them.

**Pull request merged**
