### PR TITLE
Help text in policy editor is wrapped to too wide size

### PR DESCRIPTION
**Pull request by alimirjamali**
Fixes: https://github.com/QubesOS/qubes-issues/issues/9060

### CODE REVIEW

**Comment by alimirjamali** [comment]
I appreciate if this one could be put through an Open QA test. So we could see how it looks on 1024x768 displays.

**Comment by marmarta** [comment]
PipelineRetryFailed

**Comment by marmarek** [comment]
Now the window fits on the screen (yay!), but the help text is cut (kinda expected) and there is no horizontal scrolling in the help text area to see remaining part of it...

**Comment by alimirjamali** [comment]
I am struggling to find the exact OpenQA test to see the screen snapshots.  It is not in any of `system_test_gui*` tests.

> but the help text is cut (kinda expected) and there is no horizontal scrolling in the help text area to see remaining part of it...

Yes. I did not expect it to fit horizontally on 1024 width screens. Non-existent horizontal scrolling is expected behaviour. If auto-wrap is on, GTK has to automatically break lines to fit text horizontally. Thus, there should be no need for horizontal scrolling. As I mentioned in Github issue commenting area, we have a problem on screen width less than 1366 pixels. We have too much data to show. It is possible to add a special case for 1024 width screens.

There was another bug at the moment that had to be fixed. If you try to resize the help box by its left border, it pushes the main policy area to the left instead of resizing it (like picture below). That is why line 150 & 151 are changed in PR:

policy_editor

**Comment by marmarek** [comment]
> I am struggling to find the exact OpenQA test to see the screen snapshots. It is not in any of `system_test_gui*` tests.

There is none. I took the VM disk image and started policy editor there manually...

> Yes. I did not expect it to fit horizontally on 1024 width screens.

Correction - neither scrollback is there, but scrolling via mouse wheel works in one direction (but not the other for some reason). 

policy-editor

**Comment by alimirjamali** [comment]
> Correction - neither scrollback is there, but scrolling via mouse wheel works in one direction (but not the other for some reason).

I believe I know what is happening here. The help box is cropped. I will push a fix for screens smaller than 1366 in few minutes. Hopefully 1024 pixel screen width would be the minimum requirement for Qubes OS.

**Comment by alimirjamali** [comment]
OK. I added a fix for 1024x768 displays. It includes improvements for other display sizes. As well as some minor improvements.

I am currently testing a display-manager independent Windowing area size measurement class. It uses a maximized border-less and title-less transparent dialog shown for a fraction of a second. It measures display size minus taskbar & window title bar. Fully compatible with both X11 and Wayland. Independent from themes. Hopefully it would be useful for policy editor, App Menu, Updater and other widgets in the future.

**Comment by marmarek** [comment]
> It uses a maximized border-less and title-less transparent dialog shown for a fraction of a second

Be careful, it will likely trigger override-redirect protection when used from within a VM

**Comment by alimirjamali** [comment]
> Be careful, it will likely trigger override-redirect protection when used from within a VM

Sure. Even with qubes-guid allocated two X two pixels for override_redirect VM windows, it will be much better and more comfortable than guessing the screen size and theme.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
